### ISSUE TITLE
Question/bug ?

### ISSUE THREAD

**Issue by UYScutti76** [Limiana/DynamicBridgeStandalone#1]
Hello,

Just to figure out that there might be a bug but i'm not sure, maybe i didn't understand the functionnality.
I did two different "layered designs" with 3 glamourer designs in it, so 6 glamourer designs for the total.

I then created two presets, each one selecting a different layered design.

It says in the plugin that it'll apply the designs sequentially one after another.
So i did two dynamic rules to test, each one attached to an emote and to a different preset (which are the layered designs only). I also tried with a housing location to see if the emotes were the "problem". 

The problem is that it doesn't apply sequentially the glamourer designs, it only selects the one at the bottom of the layered designs everytime.
I thought that if i'd spam the emote attached to a layered design (or any other rule), it'd show all the different glamourer designs, one after another, unless i've not understood ?

Thx for the precision if i misunderstood the functionnality :)

**Comment by Limiana** [comment]
hey, the point of layered designs is that if you have one design where you apply only gear, other one where you apply only customizations, you can basically pack these designs into one layered designs and have them apply on top of each other, forming a combined design
