### ISSUE TITLE
Cannot Apply a glamourer design to a preset

### ISSUE THREAD

**Issue by shazichan** [Limiana/DynamicBridgeStandalone#12]
I have created several presets without issue and applied appropriate glamourer designs to them but since the most recent update I have been receiving this error in the log 
![dynamicbridgelog](https://github.com/Limiana/DynamicBridgeStandalone/assets/153745814/1db73bb0-be00-4e60-bedb-0010c039f443)
and the visual error in the presets menu itself whenever i click on the glamourer dropdown menu
![dynamicbridgeerrorvisual](https://github.com/Limiana/DynamicBridgeStandalone/assets/153745814/e153d60a-29d3-4c0c-b239-9891bdf4a72a)

**Comment by Limiana** [comment]
Hello! should be fixed in version 1.0.5.5 which will be available in a couple minutes

**Comment by shazichan** [comment]
This has indeed corrected the issue thank you!
