### ISSUE TITLE
Gear/Rule Isolation

### ISSUE THREAD

**Issue by teridesu** [Limiana/DynamicBridgeStandalone#2]
Hello, i love your plugin! I just have one weird thing going on. I have 2 rules conflicting.

1- If i'm inside my house in empyreum, I will be in loungewear
2- If i'm outside in empyreum, I will equip a coat over my current gear

I am also using my original glamours for when no rules are being applied. Unfortunately, whenever i go outside the house, the coat is on top of the loungewear, instead of being my default job gear with the coat on top.
Is there a current workaround or a way to isolate the rules so it "remembers" my default game state and applies the coat based on it when I leave the house?

**Comment by Limiana** [comment]
Hello!
Unfortunately, there is no such possibility - it is not supported by Glamourer currently. But once new Glamourer version with updated IPC released, I will revisit it and see if it's possible to do so once again.

**Comment by Limiana** [comment]
@teridesu please try new Revert before application option in testing version of the plugin

**Comment by teridesu** [comment]
I may be a bit ignorant in this plugin stuff, because I don't know how to access the testing version. Could you guide me on that? Also, thank you very much for addressing my little issue!

**Comment by teridesu** [comment]
> I may be a bit ignorant in this plugin stuff, because I don't know how to access the testing version. Could you guide me on that? Also, thank you very much for addressing my little issue!

Nevermind, i figured it out! The feature you implemented seems to work, thank you very much! ＼(＾▽＾)／

I'll let you know if I find any issues.

**Comment by Limiana** [comment]
If there are any problems with this, please create another issue again
