### ISSUE TITLE
Incorrect Zone Group: The Pillars

### ISSUE THREAD

**Issue by WesBosch** [Limiana/DynamicBridgeStandalone#3]
Really funny discovery, The Pillars in Ishgard are treated as being a part of the `Hot Springs` Zone Group. Unless the Ishgardian Restoration project has something interesting going on these days, I'm sure this might be a bug. 
![image](https://github.com/Limiana/DynamicBridgeStandalone/assets/63926174/3c91d431-a27c-43dc-840c-1381cd715239)

Biome and Zone settings appear fine, all other rules and settings appear to be applying correctly as well. Foundation is correctly *not* flagged as a hot spring, but all of The Pillars seems to be.

**Comment by Limiana** [comment]
This should be corrected in latest testing version
