### ISSUE TITLE
[Bug] Drop down menu displaying issue - Weather and Grearset in Dynamic Rules

### ISSUE THREAD

**Issue by AngelFireOmega** [Limiana/DynamicBridgeStandalone#4]
Weather and Grearset drop dowm menu in Dynamic Rules will not display properly in if double byle languages are used.
![螢幕擷取畫面 2024-03-01 000922](https://github.com/Limiana/DynamicBridgeStandalone/assets/12227071/d224e5a4-57d8-44a9-949a-f698ec1095fd)
![螢幕擷取畫面 2024-03-01 000938](https://github.com/Limiana/DynamicBridgeStandalone/assets/12227071/96acf217-9a4b-4dc4-927e-abf1ac6e4bce)

**Comment by Limiana** [comment]
Hello! This bug was resolved in testing version. Please update to the testing version.
