### ISSUE TITLE
Feature Request: - Death State

### ISSUE THREAD

**Issue by shadowking1443** [Limiana/DynamicBridgeStandalone#41]
Hello,

Is it possible to add a "State" for "Death" or "Dead"? There are a few rules I'd like to implement in the event of my character's death.

**Comment by shadowking1443** [comment]
Please disregard, I forgot this was mentioned already under https://github.com/NightmareXIV/DynamicBridge/issues/24

**Comment by Limiana** [comment]
Added in upcoming 1.0.6.7
