### ISSUE TITLE
Dye Issue

### ISSUE THREAD

**Issue by RedactedHash** [Limiana/DynamicBridgeStandalone#9]
DynamicBridge doesn't appear to be properly updating the advanced necklace dyes. I have tested this by using DB to assign the glamour vs having it applied by glamourer and the behavior is different.

**Comment by Limiana** [comment]
Hello! I'm not aware of any dyeable necklaces I'm afraid?

**Comment by sneerafells** [comment]
I think the op is referring to the newish Advanced Dye feature Glamourer put out, I've also experienced recently that this feature hasnt been being copied over from Glamourer through DB.

**Comment by Limiana** [comment]
@sneerafells could you please list the exact steps to recreate the issue?

**Comment by sneerafells** [comment]
> @sneerafells could you please list the exact steps to recreate the issue?

- Open Glamouer
- Navigate to an actor
- Click Palette Icon next to gear piece
- Change a color value on said gear piece (Advanced Dying)
- Save the design
- Make preset through DB using said design
- Make dynamic rule to apply design
- The advanced dye doesn't apply to the gear piece

**Comment by Limiana** [comment]
Okay, thank you, I managed to reproduce the issue.

**Comment by Limiana** [comment]
Fixed in upcoming version
